name: caching yml file 
on:
  push: 
    branches:
      - main 

  workflow_dispatch:

jobs:
  caching_job:
    runs-on: ubuntu-latest 
    steps:
     - name : checkout repo
       uses: actions/checkout@v4

     - name : setup nodejs and automatically cache node_modules 
       uses: actions/setup-node@v4
       with:
        node-version: '20'
        cache: 'npm'

     - name: install the dependency 
       run: npm install 





"You join a new company. Their GitHub Actions pipeline is taking 8 minutes to run every time someone pushes code. A senior dev tells you npm install is the bottleneck. How do you fix this? Write the exact YAML steps."