name : Week 2 practice 1 
on: 
  push:
  workflow_dispatch: 

jobs:
  test_multiple_version: 
   runs-on: ubuntu-latest 

   strategy: 
    matrix:
      node_version: [18,20,22]

   steps:
    - name: Setup node js
      uses: actions/setup-node@v4
      with:
       node_version: ${{matrix.node_version}}

    - name: Print version
      run: |
         echo "Testing node js version ${{matrix.node_version}}"
         node -v 
         
