name: My First Workflow

on:
  push:
  workflow_dispatch:   # <--- Adds a manual "Run workflow" button in GitHub!

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Check Node
        run: node --version

      - name: Install Dependencies
        run: npm ci

      - name: Test run application syntax
        run: node -e "console.log('App check successful!')"