name: secret key test and security 

on:
 # Trigger on push  , but only on main branch 
  push:
    branches:
      - main 
    path-ignore:
      - "README.md"
  pull_request:
    branches:
      - main 
    
  # Trigger manual trigger from github action tab 
  workflow_dispatch:

jobs:
  test-and-verify-secrets:
    runs-on: ubuntu-latest

    steps:
     - name: 1. checkout code
       uses: actions/checkout@v4

     - name: 2. setup nodejs 
       uses: actions/setup-node@v4

       with:
         node-version: 20

     - name : 3. Install package
       run : npm ci

     - name : 4. Execute test script 
       run : npm test 
     - name : 5. use secret key 
       env : 
         MY_API_KEY: ${{secrets.MY_API_KEY}}
       run : |

         echo "Using secret key in workflow "

