name: Exercise 3- Quality test 

on:
 push :
  branches:
   - main 
  workflow_dispatch: 

jobs:
  run_quality_test:
   runs-on: ubuntu-latest 
    
   steps:
    - name : Step 1- Checkout Repository 
      uses: actions/checkout@v4 

    - name : Step 2 - Setup Node js 20
      uses: actions/setup-node@v4
      with:
       node-version: 20 

    - name : Step 3 Install dependence 
      run : npm ci 
    - name : Step 4 Execute Automated Unit Test 
      run: npm test 
     
     