name: Exercise 9 - Build a Docker Container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # This step reads the Dockerfile and builds the container
      - name: Build the Docker Image
        run: |
          echo "Building the Docker shipping container..."
          docker build -t my-backend-app .
      
      # This step proves the container works by turning it on!
      - name: Test the Docker Container
        run: |
          echo "Turning on the container to see what happens:"
          docker run my-backend-app
