name: week 2 artifacts
on:
  workflow_dispatch:

jobs:
  build_job:
   runs-on: ubuntu-latest 
   steps:
    - name : Create new fake app 
      run : |
          echo " This is my production backend " > backend.txt
    - name : upload artifacts to cloud 
      uses: actions/upload-artifact@v4
      with:
       name: my-package
       path: backend.txt


  deploy_job:
    needs: build_job
    runs-on: ubuntu-latest 
    steps:
     - name : Download the artifacts 
       uses: actions/download-artifact@v4
       with:
        name: my-package

     - name : Prove it is working
       run: |
          echo " Look what i successfully download from the other computer "
          cat backend.txt