name: prac 2 week 2 
on:
  push:
    branches:
      - main 
  
jobs:
  build_job:
    runs-on: ubuntu-latest 

    steps:
      - name: checkout the code 
        uses: actions/checkout@v4

      - name : build the code 
        run: npm run build

  deploy_job:
    needs: build_job
    runs-on: ubuntu-latest

    steps:
      - name : deploy to aws 
        run: |
           echo "Deploy to aws "