name: Practice 3 exercise 
on:
  push:
   branches:
   - main
   workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest 
    steps:
     - name: Checkout repo
       uses: actions/checkout@v4
     - name: Test the code
       run: |
          echo "code successfully tested"
          echo "test pass successfully"
  deploy_job:
    runs-on: ubuntu-latest
    needs: test_job
    steps:
     - name: Deploy the application 
       run: |
          echo "The application is deploye successfully "
        

      
    
