name: week 2 practice 1 Matrix 
on:
  workflow_dispatch:
jobs:
  test_multiple_version:
   runs-on: ubuntu-latest

   strategy:
    matrix:
     node_version: [18,20,22]

   steps:
    - name: Setup node js 
      uses: actions/setup-node@v4
      with:
       node-version: ${{matrix.node_version}}
    - name:
      run: |
        echo " This computer is testing node js version ${{matrix.node_version}}"
        node -v 
   
