name: practice 2
on:
  push:
   branches:
     - main 
  workflow_dispatch:

jobs:
  practice_two:
    runs-on: ubuntu-latest
    env:
     APP_ENV: "Production"
    
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Print variables and secrets
      env:
       MY_SECURE_PASSWORD: ${{secrets.MYTESTPASS}}
      run: |
       echo " The applicaiton is running in : $APP_ENV"
       echo "My super secrets password is : $MYTESTPASS"