name: Practice 4 

on:
  push:
    paths-ignore:
      - 'test.js'     # BUG 1 & 2 FIXED: Made it plural and indented to the right

jobs: 
  ignore_test:
    runs-on: ubuntu-latest
    steps: 
      - run: |        # BUG 3 FIXED: Space added after the hyphen
          echo "Ignoring path"